version: "3.4"

x-default-deploy:
  &default-deploy
  restart_policy:
    condition: on-failure
    max_attempts: 3
x-default-logging:
  &default-logging
  driver: json-file
  options:
    max-size: "1m"
    max-file: "1"
  # TODO: Add gliderlabs/logspout as a global service in a separate stack so we can pipe logs to an external service (eg: papertrail)

services:
  dispatcher:
    image: registry-special.tenforce.com/special/demonstrator-dispatcher:3.0.2
    command: ["/caddy", "-conf", "/config/Caddyfile", "-agree=true"]
    environment:
      DOMAIN: $DOMAIN
      KEYCLOAK_ENDPOINT: $KEYCLOAK_ENDPOINT
      KONG_ENDPOINT: $KONG_ENDPOINT
      XDC_ENDPOINT: $XDC_ENDPOINT
      EMAIL: $RECOVERY_EMAIL
    volumes:
    - caddycert:/root/.caddy/acme
    ports:
    - "80:2015"
    - "443:443"
    logging: *default-logging
    deploy: *default-deploy

volumes:
  caddycert: {}

networks:
  default:
    external:
      name: special-demonstrator